all : identify_line_comments

          identify_line_comments : identify_line_comments.cpp c++ -
    o identify_line_comments identify_line_comments.cpp - Wall - Wextra -
    std = c++ 17

          clean : rm -
                  r - f identify_line_comments