fastestrng: fastestrng.cpp
	clang++ --version
	clang++ -std=c++11 -O2 -fno-tree-vectorize -o fastestrng m1cycles.cpp fastestrng.cpp -Wall -Wextra
	clang++ -std=c++11 -O2 -fno-tree-vectorize -S fastestrng.cpp
clean:
	rm -r -f fastestrng
