main: example

example: example.cpp
	c++ -o example example.cpp -std=c++20

cons: cons.cpp
	c++ -o cons cons.cpp -std=c++20

failure: failure.cpp
	c++ -o failure failure.cpp -std=c++20

temp: temp.cpp
	c++ -o temp temp.cpp -std=c++20

clean:
	rm -f example failure