all: open open_pool
open : open.cpp
	c++ -o open open.cpp -O3 -Wall -Wextra -std=c++20
open_pool : open_pool.cpp
	c++ -o open_pool open_pool.cpp -O3 -Wall -Wextra -std=c++20
clean :
	rm -f open open_pool
