all: open open_poll
open : open.cpp
	c++ -o open open.cpp -O3 -Wall -Wextra -std=c++20
open_poll : open_poll.cpp
	c++ -o open_poll open_poll.cpp -O3 -Wall -Wextra -std=c++20
clean :
	rm -f open open_poll