all: utf8_length_from_latin1

utf8_length_from_latin1: utf8_length_from_latin1.cpp
	c++ -O3 -Wall utf8_length_from_latin1.cpp -o utf8_length_from_latin1 -Wall -Wextra -std=c++17

clean:
	rm -r -f utf8_length_from_latin1