all: verbose pipespeed

verbose: verbose.cpp
	c++ -std=c++17 -Wall -Wextra -o verbose verbose.cpp
pipespeed: pipespeed.cpp
	c++ -std=c++17 -Wall -Wextra -o pipespeed pipespeed.cpp
clean:
	rm -r -f verbose
